---
- name: Register Docker APT Key
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id=58118E89F3A912897C070ADBF76221572C52609D

- name: Register Docker Repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present update_cache=yes

- name: Install Docker
  apt: name=docker-engine state=present

- name: Register Vagrant User in Docker Group
  command: usermod -a -G docker vagrant

- name: Register docker default
  template: src=../templates/docker_default dest=/etc/default/docker owner=root group=root mode="0755"
  notify:
    - Restart Docker Daemon

- name: Enable dockerd Service
  service: name=docker state=started
